#!/usr/bin/env ruby
require 'rubygems'
require 'net/http'
require 'args_parser'
require 'uri'

def check(url, type)
  uri = URI.parse URI.encode url
  begin
    res = Net::HTTP.start(uri.host, uri.port).
      request(Net::HTTP::Head.new uri.request_uri)
    res.code.to_i == 200 and (!type or res.content_type =~ /#{type}/)
  rescue StandardError, Timeout::Error
    return false
  end
end

parser = ArgsParser.parse ARGV do
  arg :type, 'content-type'
  arg :help, 'show help', :alias => :h
end

if parser.has_option? :help
  STDERR.puts "#{$0} http://shokai.github.com"
  STDERR.puts "#{$0} html http://example.com/index.html"
  STDERR.puts "#{$0} image http://example.com/image.jpg"
  exit 1
end

urls = parser.argv.empty? ? STDIN.read.split(/[\r\n]+/) : parser.argv
urls.each do |url|
  next unless url =~ Regexp.new('^https?://.+$')
  puts url if check url, parser[:type]
end
